cvpvcBlog/apps/article/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns('',
    url(r'^$', 
        views.IndexView.as_view(), 
        name='index'),
    url(r'^articles$', 
        views.ArticleListView.as_view(), 
        name='article_list'),
    url(r'^articles/(?P<pk>\d+)$', 
        views.ArticleDetailView.as_view(), 
        name='detail'),
    url(r'^categories/$', 
        views.CategoriesListView.as_view(), 
        name='category_list'),
    url(r'^categories/(?P<cate_simplified_name>[a-zA-Z0-9_]+)', 
        views.CategoryArticleListView.as_view(), 
        name='cate_article_list'),
)

cvpvcBlog/apps/mini_url/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^full_list/', views.FullListView.as_view(), name='full_list'),
    url(r'^new_url/', views.new_url, name='new_url'),
    url(r'^(?P<code>[a-zA-Z0-9]*)', views.short, name='short'),
)

cvpvcBlog/apps/picture/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns('',
    url(r'^$', views.ImageView.as_view(), name='images'),
)

cvpvcBlog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^m/', include('cvpvcBlog.apps.mini_url.urls', namespace='miniurl')),
    url(r'^images/', include('cvpvcBlog.apps.picture.urls', namespace='picture')),
    url(r'^', include('cvpvcBlog.apps.article.urls', namespace='blog')),
)

from django.conf import settings
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),)
    

cvpvcBlog/apps/article/models.py
# -*- coding: utf-8 -*-

import re

from django.db import models

class Article(models.Model):
    """
        A very simple model for articles that contains only the title,
        the content and the date of publication
    """
    title = models.CharField(
        max_length=255, 
        unique_for_date='publication_date',
        verbose_name='Titre de l\'article')
    publication_date = models.DateField(
        auto_now=False, 
        auto_now_add=True,
        verbose_name='Date d\'ajout')
    last_edited = models.DateField(
        auto_now=True, 
        auto_now_add=True,
        verbose_name='Dernière modification')
    content = models.TextField(verbose_name='Contenu de l\'article')
    nb_of_view = models.PositiveIntegerField(
        default=0,
        verbose_name='Nombre de vues')
    category = models.ForeignKey('Category')

    def __unicode__(self):
        return u'{titre} - {pub_date}'.format(
            titre=self.title, 
            pub_date=self.publication_date)

class Comment(models.Model):
    """
        Simple comment model. Only I will be able to had comment for now
    """
    article = models.ForeignKey('Article')
    pseudo = models.CharField(max_length=255, verbose_name='Pseudo')
    content = models.TextField(verbose_name='Contenu du commentaire')
    publication_date = models.DateField(
        auto_now=False, 
        auto_now_add=True,
        verbose_name='Date de publication')

class Category(models.Model):
    """
        Simple category for the articles
    """
    name = models.CharField(
        max_length=255, 
        unique=True,
        verbose_name='Nom de la catégorie')
    simplified_name = models.CharField(
        max_length=254,
        verbose_name='Nom simplifié de la catégorie')

    def __unicode__(self):
        return u'{}'.format(self.name)

    def save(self, *args, **kwargs):
        if self.name:
            self.simplified_name = re.sub(r'[^a-zA-Z0-9_]', '_',
                self.name.lower())
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Catégorie'

cvpvcBlog/apps/mini_url/models.py
#-*- coding: utf-8 -*-

import random
import string

from django.db import models

class MiniURL(models.Model):
    """
        Model that takes the mini-URLs and save them
    """
    long_url = models.URLField(unique=True, verbose_name='Longue Url')
    code = models.CharField(unique=True, max_length=200, verbose_name='Code pour identifier l\'URL')
    date_creation = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name='Date de creation du lien')
    pseudo = models.CharField(max_length=200, blank=True, verbose_name='Pseudo')
    title = models.CharField(max_length=200, blank=True, verbose_name='Titre de la page')
    nb_of_access = models.IntegerField(default=0, verbose_name='Nombre d\'accès au lien')

    def __unicode__(self):
        """
            The representation sends back the long URL and the code
        """
        return 'URL : {} - CODE : {}'.format(self.long_url, self.url_code)

    def save(self, *args, **kwargs):
        """
            Rewriting the save method to include the code generating
        """
        if self.pk is None:
            self.mixing_url(5)
        super(MiniURL, self).save(*args, **kwargs)

    def mixing_url(self, N):
        """
            Generate a string of size N and checks if it already exists
        """
        is_code_unique = False
        while not is_code_unique:
            char_to_use = list(string.ascii_letters + string.digits)
            random.shuffle(char_to_use)
            random_code = ''.join([letter for letter in char_to_use[:N]])
            try:
                MiniURL.objects.get(code=random_code)
            except MiniURL.DoesNotExist:
                self.code = random_code
                is_code_unique = True

cvpvcBlog/apps/picture/models.py
# -*- coding: utf-8 -*-

from django.db import models

class Picture(models.Model):
    """
        picture management logic is going to be defined here.
    """
    title = models.CharField(
        max_length=255, 
        unique=True,
        verbose_name='Titre de l\'image',)
    image = models.ImageField(upload_to='img/')

    def __unicode__(self):
        return u'{}'.format(self.title)

cvpvcBlog/apps/viewer/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User

class Viewer(models.Model):
    user = models.OneToOneField(User)

cvpvcBlog/apps/mini_url/forms.py
#-*- coding: utf-8 -*-

from django import forms
from .models import MiniURL

class MiniURLForm(forms.ModelForm):
    class Meta:
        model = MiniURL
        fields = ['long_url', 'pseudo']

    def __init__(self, *args, **kwargs):
        super(MiniURLForm, self).__init__(*args, **kwargs)
        self.fields['long_url'].widget.attrs.update({'class' : 'form-control'})
        self.fields['pseudo'].widget.attrs.update({'class' : 'form-control'})

cvpvcBlog/apps/article/views.py
#-*- coding: utf-8 -*-

from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Article, Category, Comment

class IndexView(generic.ListView):
    """
        Welcome page with the list of all the different articles
    """
    model = Article
    template_name = 'article/index.html'
    context_object_name = 'articles_list'

    def get_queryset(self):
        """
            returns the list of all articles
        """
        return Article.objects.order_by('-publication_date')[:10]

class ArticleListView(generic.ListView):
    """
        Welcome page with the list of all the different articles
    """
    model = Article
    template_name = 'article/articles_list.html'
    context_object_name = 'articles_list'

    def get_queryset(self):
        """
            returns the list of all articles
        """
        return Article.objects.order_by('-publication_date')

class ArticleDetailView(generic.DetailView):
    """
        Detail of the article number pk
    """
    model = Article
    template_name = 'article/article_detail.html'
    context_object_name = 'article'

    def get_object(self, queryset=None):
        """
            Customization of the function to save the number of views
        """
        art = super(ArticleDetailView, self).get_object(queryset)
        art.nb_of_view += 1
        art.save()
        return art

class CategoriesListView(generic.ListView):
    """
        List of all categories
    """
    model = Category
    template_name = 'article/categories_list.html'
    context_object_name = 'categories_list'

    def get_queryset(self):
        """
            returns the list of all categories
        """
        return Category.objects.all()

class CategoryArticleListView(generic.ListView):
    """
        List of all article within one category
    """
    model = Article
    template_name = 'article/cate_articles_list.html'
    context_object_name = 'cate_article_list'

    def get_queryset(self):
        """
            returns the list of all categories
        """
        return Article.objects.filter(
                category__simplified_name=self.kwargs['cate_simplified_name']
            ).order_by(
                '-publication_date'
            )

    def get_context_data(self, **kwargs):
        """
            adding the category object to the context variables
        """
        context = super(CategoryArticleListView, self).get_context_data(
            **kwargs)
        context['category'] = Category.objects.get(
            simplified_name=self.kwargs['cate_simplified_name'])
        return context

cvpvcBlog/apps/mini_url/views.py
#-*- coding: utf-8 -*-

from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic

import requests
from bs4 import BeautifulSoup

from .forms import MiniURLForm
from .models import MiniURL

class IndexView(generic.ListView):
    """
        View that manages what the user sees when arriving on the url shortener
    """
    model = MiniURL
    template_name = 'mini_url/welcome_page.html'
    context_object_name = 'latest_mini_url_list'

    def get_queryset(self):
        """
            Returns the last 5 url shortened
        """
        return MiniURL.objects.order_by('-date_creation')[:5]

class FullListView(generic.ListView):
    """
        View that sends all the shortened URLs orderer by date
    """
    model = MiniURL
    template_name = 'mini_url/full_list.html'
    context_object_name = 'full_mini_url_list'

    def get_queryset(self):
        """
            Returns the last 5 url shortened
        """
        return MiniURL.objects.order_by('-date_creation')

def new_url(request):
    """
        Form to get a new url and process data sent.
    """
    if request.method == 'POST':
        form = MiniURLForm(request.POST)

        if form.is_valid():
            long_url = form.cleaned_data['long_url']
            pseudo = form.cleaned_data['pseudo']

            miniurl = MiniURL()
            miniurl.long_url = long_url
            miniurl.pseudo = pseudo

            try:
                res = requests.get(miniurl.long_url)
            except:
                miniurl.title = 'Page Not Found'
            else:
                if res.status_code != 200:
                    miniurl.title = 'Page Not Found'
                else:
                    try:
                        soup = BeautifulSoup(res.content)
                    except:
                        miniurl.title = 'Page Not Found'
                    else:
                        miniurl.title = soup.title.string

            miniurl.save()

            status = 'URL saved'

        else:
            status = 'Remplissez correctement le formulaire'

    else:
        form = MiniURLForm(label_suffix='')

    template_name = 'mini_url/miniurl_form.html'
    return render(request, template_name, locals())

def short(request, code):
    """
        View that redirects to the link or to 404 error page
    """
    miniurl = get_object_or_404(MiniURL, code=code)
    miniurl.nb_of_access += 1
    miniurl.save()
    return redirect(miniurl.long_url)

cvpvcBlog/apps/picture/views.py
#-*- coding: utf-8 -*-

from django.views import generic

from .models import Picture

class ImageView(generic.ListView):
    """
        This view is the gallery of the website with all the pictures taken.
    """
    model = Picture
    template_name = 'article/gallery.html'
    context_object_name = 'images'

cvpvcBlog/apps/viewer/views.py
from django.shortcuts import render

# Create your views here.

cvpvcBlog/templates/article/article_detail.html
{% extends 'website.html' %}
{% load static %}
{% load markdown_filter %}

{% block style %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% if article.category.simplified_name == "pvc" %}
<link rel="stylesheet" href="{% static 'css/prism.css' %}">
{% endif %}
{% endblock %}

{% block title %}
CVPVC Blog | {{ article.title }}
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center page-header">
            <h1>{{ article.title}}</h1>
            <h3 class="lead">{{ article.publication_date }}
                {% ifnotequal article.publication_date article.last_edited %}
                <small>- dernière modif {{ article.last_edited }}</small>
                {% endifnotequal %}
            </h3>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 article_content">
                {% if article.category.simplified_name == "pvc" %}
                    {{ article.content | safe }}
                {% else %}
                    {{ article.content | markdownify | safe }}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
{{ block.super }}
{% if article.category.simplified_name == "pvc" %}
<script src="{% static 'js/lib/prism.js' %}"></script>
<script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
{% else %}
<script src="{% static 'js/mardown_center_img.js' %}"></script>
{% endif %}
{% endblock %}

cvpvcBlog/templates/article/articles_list.html
{% extends 'website.html' %}
{% load static %}

{% block style %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block title %}
CVPVC Blog | Liste des Articles
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center page-header">
            <h1 class="main">Tous les articles</h1>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="container article_list_container">
    {% for article in articles_list %}
        {% if article.category.name != "Test" %}
        <div class="row">
            <div class="col-md-8 col-md-offset-2 article_list">
                <h4>
                    <a href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a><small> - {{ article.publication_date }}</small>
                </h4>
            </div>
        </div>
        {% endif %}
    {% empty %}
        <div class="row">
            <div class="col-md-8 col-lg-offset-2">Pas d'articles enregistrées</div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

cvpvcBlog/templates/article/cate_articles_list.html
{% extends 'website.html' %}
{% load static %}

{% block style %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block title %}
CVPVC Blog | {{ category.name }}
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center page-header">
            <h1 class="main">Articles de la catégorie {{ category.name }}</h1>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="container">
    {% for article in cate_article_list %}
        <div class="row">
            <div class="col-md-8 col-md-offset-2 article_list">
                <h4>
                    <a href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a><small> - {{ article.publication_date }}</small>
                </h4>
            </div>
        </div>
    {% empty %}
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                Pas d'articles dans cette catégorie pour le moment.
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

cvpvcBlog/templates/article/categories_list.html
{% extends 'website.html' %}
{% load static %}

{% block style %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block title %}
CVPVC Blog | Liste des Catégories
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center page-header">
            <h1 class="main">Liste des Catégories</h1>
            <h3 class="lead">les liens mêmes vers les listes d'articles par catégories</h3>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="row">
                {% for category in categories_list %}
                    {% if category.name != "Test" %}
                    <a href="{% url 'blog:cate_article_list' category.simplified_name %}"><div class="col-xs-6 col-sm-4 col-md-3 text-center">
                        <div class='square-box'>
                            <div class='square-content'>
                                <div>
                                    <span><strong>{{ category.name }}</strong></span>
                                </div>
                            </div>
                        </div>
                    </div></a>
                    {% endif %}
                {% empty %}
                Pas de catégories trouvées
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

cvpvcBlog/templates/article/gallery.html
{% extends 'website.html' %}
{% load static %}

{% block style %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block title %}
CVPVC Blog | Gallerie
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center page-header">
            <h1 class="main">Galerie de notre voyage</h1>
            <h3 class="lead">Cliquer sur les photos pour les voir en grand. Vous pouvez utiliser les flèches pour vous déplacer.</h3>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row" id="msry-container">
            <div class="col-md-8 col-md-offset-2">
                <div class="row">
                {% for image in images %}
                <img src="{{ image.image.url }}" alt="{{ image.title }}" data-img-nb="{{ forloop.counter0 }}" data-img-total-nb="{{ images.count }}" class="img-responsive img_gallery
                col-sm-4 col-xs-12
                {% comment %}
                {% if image.image.height > image.image.width %}
                    col-sm-2 col-xs-6
                {% else %}
                    col-sm-4 col-xs-12
                {% endif %}
                {% endcomment %}
                ">
                {% empty %}
                Pas de photos
                {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="img_modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="false">&times;</span></button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-12" id="img_modal_content">
                                <img src="" data-img-nb="" class="img-responsive">
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
{% endblock %}

{% block js %}
{{ block.super }}
<script src="{% static 'js/function.js' %}"></script>
{% endblock %}

cvpvcBlog/templates/article/index.html
{% extends 'website.html' %}
{% load static %}

{% block style %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
    <div class="container article_list_container">
    {% for article in articles_list %}
        {% if article.category.name != "Test" %}
        <div class="row">
            <div class="col-md-8 col-md-offset-2 article_list">
                <h4><a href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a> <small> - {{ article.publication_date }}</small>
                </h4>
            </div>
        </div>
        {% endif %}
    {% empty %}
        <div class="row">
            <div class="col-md-8 col-lg-offset-2">Pas d'articles enregistrées</div>
        </div>
    {% endfor %}
    </div>
{% endblock %}