cvpvcBlog/apps/article/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns('',
    url(r'^$', 
        views.IndexView.as_view(), 
        name='index'),
    url(r'^articles$', 
        views.ArticleListView.as_view(), 
        name='article_list'),
    url(r'^articles/(?P<pk>\d+)$', 
        views.ArticleDetailView.as_view(), 
        name='detail'),
    url(r'^categories/$', 
        views.CategoriesListView.as_view(), 
        name='category_list'),
    url(r'^categories/(?P<cate_simplified_name>[a-zA-Z0-9_]+)', 
        views.CategoryArticleListView.as_view(), 
        name='cate_article_list'),
)

cvpvcBlog/apps/mini_url/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^full_list/', views.FullListView.as_view(), name='full_list'),
    url(r'^new_url/', views.new_url, name='new_url'),
    url(r'^(?P<code>[a-zA-Z0-9]*)', views.short, name='short'),
)

cvpvcBlog/apps/picture/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns('',
    url(r'^$', views.ImageView.as_view(), name='images'),
)

cvpvcBlog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^m/', include('cvpvcBlog.apps.mini_url.urls', namespace='miniurl')),
    url(r'^images/', include('cvpvcBlog.apps.picture.urls', namespace='picture')),
    url(r'^', include('cvpvcBlog.apps.article.urls', namespace='blog')),
)

from django.conf import settings
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),)
    

cvpvcBlog/apps/article/models.py
# -*- coding: utf-8 -*-

import re

from django.db import models

class Article(models.Model):
    """
        A very simple model for articles that contains only the title,
        the content and the date of publication
    """
    title = models.CharField(
        max_length=255, 
        unique_for_date='publication_date',
        verbose_name='Titre de l\'article')
    publication_date = models.DateField(
        auto_now=False, 
        auto_now_add=True,
        verbose_name='Date d\'ajout')
    last_edited = models.DateField(
        auto_now=True, 
        auto_now_add=True,
        verbose_name='Dernière modification')
    content = models.TextField(verbose_name='Contenu de l\'article')
    nb_of_view = models.PositiveIntegerField(
        default=0,
        verbose_name='Nombre de vues')
    category = models.ForeignKey('Category')

    def __unicode__(self):
        return u'{titre} - {pub_date}'.format(
            titre=self.title, 
            pub_date=self.publication_date)

class Comment(models.Model):
    """
        Simple comment model. Only I will be able to had comment for now
    """
    article = models.ForeignKey('Article')
    pseudo = models.CharField(max_length=255, verbose_name='Pseudo')
    content = models.TextField(verbose_name='Contenu du commentaire')
    publication_date = models.DateField(
        auto_now=False, 
        auto_now_add=True,
        verbose_name='Date de publication')

class Category(models.Model):
    """
        Simple category for the articles
    """
    name = models.CharField(
        max_length=255, 
        unique=True,
        verbose_name='Nom de la catégorie')
    simplified_name = models.CharField(
        max_length=254,
        verbose_name='Nom simplifié de la catégorie')

    def __unicode__(self):
        return u'{}'.format(self.name)

    def save(self, *args, **kwargs):
        if self.name:
            self.simplified_name = re.sub(r'[^a-zA-Z0-9_]', '_',
                self.name.lower())
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Catégorie'

cvpvcBlog/apps/mini_url/models.py
#-*- coding: utf-8 -*-

import random
import string

from django.db import models

class MiniURL(models.Model):
    """
        Model that takes the mini-URLs and save them
    """
    long_url = models.URLField(unique=True, verbose_name='Longue Url')
    code = models.CharField(unique=True, max_length=200, verbose_name='Code pour identifier l\'URL')
    date_creation = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name='Date de creation du lien')
    pseudo = models.CharField(max_length=200, blank=True, verbose_name='Pseudo')
    title = models.CharField(max_length=200, blank=True, verbose_name='Titre de la page')
    nb_of_access = models.IntegerField(default=0, verbose_name='Nombre d\'accès au lien')

    def __unicode__(self):
        """
            The representation sends back the long URL and the code
        """
        return 'URL : {} - CODE : {}'.format(self.long_url, self.url_code)

    def save(self, *args, **kwargs):
        """
            Rewriting the save method to include the code generating
        """
        if self.pk is None:
            self.mixing_url(5)
        super(MiniURL, self).save(*args, **kwargs)

    def mixing_url(self, N):
        """
            Generate a string of size N and checks if it already exists
        """
        is_code_unique = False
        while not is_code_unique:
            char_to_use = list(string.ascii_letters + string.digits)
            random.shuffle(char_to_use)
            random_code = ''.join([letter for letter in char_to_use[:N]])
            try:
                MiniURL.objects.get(code=random_code)
            except MiniURL.DoesNotExist:
                self.code = random_code
                is_code_unique = True

cvpvcBlog/apps/picture/models.py
# -*- coding: utf-8 -*-

from django.db import models

class Picture(models.Model):
    """
        picture management logic is going to be defined here.
    """
    title = models.CharField(
        max_length=255, 
        unique=True,
        verbose_name='Titre de l\'image',)
    image = models.ImageField(upload_to='img/')

    def __unicode__(self):
        return u'{}'.format(self.title)

cvpvcBlog/apps/viewer/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User

class Viewer(models.Model):
    user = models.OneToOneField(User)

cvpvcBlog/apps/mini_url/forms.py
#-*- coding: utf-8 -*-

from django import forms
from .models import MiniURL

class MiniURLForm(forms.ModelForm):
    class Meta:
        model = MiniURL
        fields = ['long_url', 'pseudo']

    def __init__(self, *args, **kwargs):
        super(MiniURLForm, self).__init__(*args, **kwargs)
        self.fields['long_url'].widget.attrs.update({'class' : 'form-control'})
        self.fields['pseudo'].widget.attrs.update({'class' : 'form-control'})

cvpvcBlog/apps/article/views.py
#-*- coding: utf-8 -*-

from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Article, Category, Comment

class IndexView(generic.ListView):
    """
        Welcome page with the list of all the different articles
    """
    model = Article
    template_name = 'article/index.html'
    context_object_name = 'articles_list'

    def get_queryset(self):
        """
            returns the list of all articles
        """
        return Article.objects.order_by('-publication_date')[:10]

class ArticleListView(generic.ListView):
    """
        Welcome page with the list of all the different articles
    """
    model = Article
    template_name = 'article/articles_list.html'
    context_object_name = 'articles_list'

    def get_queryset(self):
        """
            returns the list of all articles
        """
        return Article.objects.order_by('-publication_date')

class ArticleDetailView(generic.DetailView):
    """
        Detail of the article number pk
    """
    model = Article
    template_name = 'article/article_detail.html'
    context_object_name = 'article'

    def get_object(self, queryset=None):
        """
            Customization of the function to save the number of views
        """
        art = super(ArticleDetailView, self).get_object(queryset)
        art.nb_of_view += 1
        art.save()
        return art

class CategoriesListView(generic.ListView):
    """
        List of all categories
    """
    model = Category
    template_name = 'article/categories_list.html'
    context_object_name = 'categories_list'

    def get_queryset(self):
        """
            returns the list of all categories
        """
        return Category.objects.all()

class CategoryArticleListView(generic.ListView):
    """
        List of all article within one category
    """
    model = Article
    template_name = 'article/cate_articles_list.html'
    context_object_name = 'cate_article_list'

    def get_queryset(self):
        """
            returns the list of all categories
        """
        return Article.objects.filter(
                category__simplified_name=self.kwargs['cate_simplified_name']
            ).order_by(
                '-publication_date'
            )

    def get_context_data(self, **kwargs):
        """
            adding the category object to the context variables
        """
        context = super(CategoryArticleListView, self).get_context_data(
            **kwargs)
        context['category'] = Category.objects.get(
            simplified_name=self.kwargs['cate_simplified_name'])
        return context

cvpvcBlog/apps/mini_url/views.py
#-*- coding: utf-8 -*-

from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic

import requests
from bs4 import BeautifulSoup

from .forms import MiniURLForm
from .models import MiniURL

class IndexView(generic.ListView):
    """
        View that manages what the user sees when arriving on the url shortener
    """
    model = MiniURL
    template_name = 'mini_url/welcome_page.html'
    context_object_name = 'latest_mini_url_list'

    def get_queryset(self):
        """
            Returns the last 5 url shortened
        """
        return MiniURL.objects.order_by('-date_creation')[:5]

class FullListView(generic.ListView):
    """
        View that sends all the shortened URLs orderer by date
    """
    model = MiniURL
    template_name = 'mini_url/full_list.html'
    context_object_name = 'full_mini_url_list'

    def get_queryset(self):
        """
            Returns the last 5 url shortened
        """
        return MiniURL.objects.order_by('-date_creation')

def new_url(request):
    """
        Form to get a new url and process data sent.
    """
    if request.method == 'POST':
        form = MiniURLForm(request.POST)

        if form.is_valid():
            long_url = form.cleaned_data['long_url']
            pseudo = form.cleaned_data['pseudo']

            miniurl = MiniURL()
            miniurl.long_url = long_url
            miniurl.pseudo = pseudo

            try:
                res = requests.get(miniurl.long_url)
            except:
                miniurl.title = 'Page Not Found'
            else:
                if res.status_code != 200:
                    miniurl.title = 'Page Not Found'
                else:
                    try:
                        soup = BeautifulSoup(res.content)
                    except:
                        miniurl.title = 'Page Not Found'
                    else:
                        miniurl.title = soup.title.string

            miniurl.save()

            status = 'URL saved'

        else:
            status = 'Remplissez correctement le formulaire'

    else:
        form = MiniURLForm(label_suffix='')

    template_name = 'mini_url/miniurl_form.html'
    return render(request, template_name, locals())

def short(request, code):
    """
        View that redirects to the link or to 404 error page
    """
    miniurl = get_object_or_404(MiniURL, code=code)
    miniurl.nb_of_access += 1
    miniurl.save()
    return redirect(miniurl.long_url)

cvpvcBlog/apps/picture/views.py
#-*- coding: utf-8 -*-

from django.views import generic

from .models import Picture

class ImageView(generic.ListView):
    """
        This view is the gallery of the website with all the pictures taken.
    """
    model = Picture
    template_name = 'article/gallery.html'
    context_object_name = 'images'

cvpvcBlog/apps/viewer/views.py
from django.shortcuts import render

# Create your views here.

cvpvcBlog/templates/website.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <link rel="icon" type="image/png" href="{% static 'img/favicons/favicon-32x32.png' %}" sizes="32x32">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media
        queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file://
        -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script> <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script> <![endif]-->
{% block meta %}
{% endblock %}
        
{% block style %}
            <link href='http://fonts.googleapis.com/css?family=Playfair+Display' rel='stylesheet' type='text/css'>
            <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
{% endblock %}
        
        <title>
            {% block title %}CVPVC Blog{% endblock %}
        </title>
    </head>
    <body>
{% block nav %}
        <nav class="text-center">
            <a data-toggle="tooltip" href="{% url 'blog:index' %}" title="Accueil"><span class="glyphicon glyphicon-home"></span></a>
            <a data-toggle="tooltip" href="{% url 'blog:article_list' %}" title="Liste des articles"><span class="glyphicon glyphicon-align-justify"></span></a>
            <a data-toggle="tooltip" href="{% url 'blog:category_list' %}" title="Liste des catégories"><span class="glyphicon glyphicon-th"></span></a>
            <a data-toggle="tooltip" href="{% url 'picture:images' %}" title="Toutes nos photos"><span class="glyphicon glyphicon-camera"></span></a>
        </nav>
{% endblock %}
     
{% block header %}
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center page-header">
                    <h1 class="main">Bienvenue sur notre blog !</h1>
                    <img src="{% static 'img/logo_cvpvc.png' %}" alt="Logo">
                    <h3 class="lead">CVPVC est le blog de Claire Verney et Pierre-Victor Chaumier</h3>
                </div>
            </div>
        </div>
{% endblock %}
        
{% block content %}
            <h2>Bienvenue sur notre blog !</h2>
{% endblock %}
        
        <div class="push"></div>

        <footer class="footer">
{% block footer %}
            <div class="container">
                <div class="text-muted text-center">
                    © Pierre-Victor Chaumier
                    <br>Design made using <a href="http://www.getbootstrap.com">Bootstrap 3</a> and to <a href="http://glyphicons.com/">Glyphicon</a>
                    <br>Web site developped using <a href="https://docs.djangoproject.com/">Django Framework</a>
                    <br>(thanks guys, you rock !)
                </div>
            </div>
{% endblock %}
        </footer>

{% block js %}
        <script src="{% static 'js/lib/jquery-2.1.1.min.js' %}"></script>
        <script src="{% static 'js/lib/bootstrap.min.js' %}"></script>
        <script>
            $(function (){
                $('a').tooltip(); 
            });
        </script>
{% endblock %}
    </body>
</html>