cvpvcBlog/apps/article/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns('',
    url(r'^$', 
        views.IndexView.as_view(), 
        name='index'),
    url(r'^articles$', 
        views.ArticleListView.as_view(), 
        name='article_list'),
    url(r'^articles/(?P<pk>\d+)$', 
        views.ArticleDetailView.as_view(), 
        name='detail'),
    url(r'^categories/$', 
        views.CategoriesListView.as_view(), 
        name='category_list'),
    url(r'^categories/(?P<cate_simplified_name>[a-zA-Z0-9_]+)', 
        views.CategoryArticleListView.as_view(), 
        name='cate_article_list'),
)

cvpvcBlog/apps/mini_url/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^full_list/', views.FullListView.as_view(), name='full_list'),
    url(r'^new_url/', views.new_url, name='new_url'),
    url(r'^(?P<code>[a-zA-Z0-9]*)', views.short, name='short'),
)

cvpvcBlog/apps/picture/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns('',
    url(r'^$', views.ImageView.as_view(), name='images'),
)

cvpvcBlog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^m/', include('cvpvcBlog.apps.mini_url.urls', namespace='miniurl')),
    url(r'^images/', include('cvpvcBlog.apps.picture.urls', namespace='picture')),
    url(r'^', include('cvpvcBlog.apps.article.urls', namespace='blog')),
)

from django.conf import settings
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),)
    

cvpvcBlog/apps/article/models.py
# -*- coding: utf-8 -*-

import re

from django.db import models

class Article(models.Model):
    """
        A very simple model for articles that contains only the title,
        the content and the date of publication
    """
    title = models.CharField(
        max_length=255, 
        unique_for_date='publication_date',
        verbose_name='Titre de l\'article')
    publication_date = models.DateField(
        auto_now=False, 
        auto_now_add=True,
        verbose_name='Date d\'ajout')
    last_edited = models.DateField(
        auto_now=True, 
        auto_now_add=True,
        verbose_name='Dernière modification')
    content = models.TextField(verbose_name='Contenu de l\'article')
    nb_of_view = models.PositiveIntegerField(
        default=0,
        verbose_name='Nombre de vues')
    category = models.ForeignKey('Category')

    def __unicode__(self):
        return u'{titre} - {pub_date}'.format(
            titre=self.title, 
            pub_date=self.publication_date)

class Comment(models.Model):
    """
        Simple comment model. Only I will be able to had comment for now
    """
    article = models.ForeignKey('Article')
    pseudo = models.CharField(max_length=255, verbose_name='Pseudo')
    content = models.TextField(verbose_name='Contenu du commentaire')
    publication_date = models.DateField(
        auto_now=False, 
        auto_now_add=True,
        verbose_name='Date de publication')

class Category(models.Model):
    """
        Simple category for the articles
    """
    name = models.CharField(
        max_length=255, 
        unique=True,
        verbose_name='Nom de la catégorie')
    simplified_name = models.CharField(
        max_length=254,
        verbose_name='Nom simplifié de la catégorie')

    def __unicode__(self):
        return u'{}'.format(self.name)

    def save(self, *args, **kwargs):
        if self.name:
            self.simplified_name = re.sub(r'[^a-zA-Z0-9_]', '_',
                self.name.lower())
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Catégorie'

cvpvcBlog/apps/mini_url/models.py
#-*- coding: utf-8 -*-

import random
import string

from django.db import models

class MiniURL(models.Model):
    """
        Model that takes the mini-URLs and save them
    """
    long_url = models.URLField(unique=True, verbose_name='Longue Url')
    code = models.CharField(unique=True, max_length=200, verbose_name='Code pour identifier l\'URL')
    date_creation = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name='Date de creation du lien')
    pseudo = models.CharField(max_length=200, blank=True, verbose_name='Pseudo')
    title = models.CharField(max_length=200, blank=True, verbose_name='Titre de la page')
    nb_of_access = models.IntegerField(default=0, verbose_name='Nombre d\'accès au lien')

    def __unicode__(self):
        """
            The representation sends back the long URL and the code
        """
        return 'URL : {} - CODE : {}'.format(self.long_url, self.url_code)

    def save(self, *args, **kwargs):
        """
            Rewriting the save method to include the code generating
        """
        if self.pk is None:
            self.mixing_url(5)
        super(MiniURL, self).save(*args, **kwargs)

    def mixing_url(self, N):
        """
            Generate a string of size N and checks if it already exists
        """
        is_code_unique = False
        while not is_code_unique:
            char_to_use = list(string.ascii_letters + string.digits)
            random.shuffle(char_to_use)
            random_code = ''.join([letter for letter in char_to_use[:N]])
            try:
                MiniURL.objects.get(code=random_code)
            except MiniURL.DoesNotExist:
                self.code = random_code
                is_code_unique = True

cvpvcBlog/apps/picture/models.py
# -*- coding: utf-8 -*-

from django.db import models

class Picture(models.Model):
    """
        picture management logic is going to be defined here.
    """
    title = models.CharField(
        max_length=255, 
        unique=True,
        verbose_name='Titre de l\'image',)
    image = models.ImageField(upload_to='img/')

    def __unicode__(self):
        return u'{}'.format(self.title)

cvpvcBlog/apps/viewer/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User

class Viewer(models.Model):
    user = models.OneToOneField(User)

cvpvcBlog/apps/mini_url/forms.py
#-*- coding: utf-8 -*-

from django import forms
from .models import MiniURL

class MiniURLForm(forms.ModelForm):
    class Meta:
        model = MiniURL
        fields = ['long_url', 'pseudo']

    def __init__(self, *args, **kwargs):
        super(MiniURLForm, self).__init__(*args, **kwargs)
        self.fields['long_url'].widget.attrs.update({'class' : 'form-control'})
        self.fields['pseudo'].widget.attrs.update({'class' : 'form-control'})

cvpvcBlog/apps/article/views.py
#-*- coding: utf-8 -*-

from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Article, Category, Comment

class IndexView(generic.ListView):
    """
        Welcome page with the list of all the different articles
    """
    model = Article
    template_name = 'article/index.html'
    context_object_name = 'articles_list'

    def get_queryset(self):
        """
            returns the list of all articles
        """
        return Article.objects.order_by('-publication_date')[:10]

class ArticleListView(generic.ListView):
    """
        Welcome page with the list of all the different articles
    """
    model = Article
    template_name = 'article/articles_list.html'
    context_object_name = 'articles_list'

    def get_queryset(self):
        """
            returns the list of all articles
        """
        return Article.objects.order_by('-publication_date')

class ArticleDetailView(generic.DetailView):
    """
        Detail of the article number pk
    """
    model = Article
    template_name = 'article/article_detail.html'
    context_object_name = 'article'

    def get_object(self, queryset=None):
        """
            Customization of the function to save the number of views
        """
        art = super(ArticleDetailView, self).get_object(queryset)
        art.nb_of_view += 1
        art.save()
        return art

class CategoriesListView(generic.ListView):
    """
        List of all categories
    """
    model = Category
    template_name = 'article/categories_list.html'
    context_object_name = 'categories_list'

    def get_queryset(self):
        """
            returns the list of all categories
        """
        return Category.objects.all()

class CategoryArticleListView(generic.ListView):
    """
        List of all article within one category
    """
    model = Article
    template_name = 'article/cate_articles_list.html'
    context_object_name = 'cate_article_list'

    def get_queryset(self):
        """
            returns the list of all categories
        """
        return Article.objects.filter(
                category__simplified_name=self.kwargs['cate_simplified_name']
            ).order_by(
                '-publication_date'
            )

    def get_context_data(self, **kwargs):
        """
            adding the category object to the context variables
        """
        context = super(CategoryArticleListView, self).get_context_data(
            **kwargs)
        context['category'] = Category.objects.get(
            simplified_name=self.kwargs['cate_simplified_name'])
        return context

cvpvcBlog/apps/mini_url/views.py
#-*- coding: utf-8 -*-

from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic

import requests
from bs4 import BeautifulSoup

from .forms import MiniURLForm
from .models import MiniURL

class IndexView(generic.ListView):
    """
        View that manages what the user sees when arriving on the url shortener
    """
    model = MiniURL
    template_name = 'mini_url/welcome_page.html'
    context_object_name = 'latest_mini_url_list'

    def get_queryset(self):
        """
            Returns the last 5 url shortened
        """
        return MiniURL.objects.order_by('-date_creation')[:5]

class FullListView(generic.ListView):
    """
        View that sends all the shortened URLs orderer by date
    """
    model = MiniURL
    template_name = 'mini_url/full_list.html'
    context_object_name = 'full_mini_url_list'

    def get_queryset(self):
        """
            Returns the last 5 url shortened
        """
        return MiniURL.objects.order_by('-date_creation')

def new_url(request):
    """
        Form to get a new url and process data sent.
    """
    if request.method == 'POST':
        form = MiniURLForm(request.POST)

        if form.is_valid():
            long_url = form.cleaned_data['long_url']
            pseudo = form.cleaned_data['pseudo']

            miniurl = MiniURL()
            miniurl.long_url = long_url
            miniurl.pseudo = pseudo

            try:
                res = requests.get(miniurl.long_url)
            except:
                miniurl.title = 'Page Not Found'
            else:
                if res.status_code != 200:
                    miniurl.title = 'Page Not Found'
                else:
                    try:
                        soup = BeautifulSoup(res.content)
                    except:
                        miniurl.title = 'Page Not Found'
                    else:
                        miniurl.title = soup.title.string

            miniurl.save()

            status = 'URL saved'

        else:
            status = 'Remplissez correctement le formulaire'

    else:
        form = MiniURLForm(label_suffix='')

    template_name = 'mini_url/miniurl_form.html'
    return render(request, template_name, locals())

def short(request, code):
    """
        View that redirects to the link or to 404 error page
    """
    miniurl = get_object_or_404(MiniURL, code=code)
    miniurl.nb_of_access += 1
    miniurl.save()
    return redirect(miniurl.long_url)

cvpvcBlog/apps/picture/views.py
#-*- coding: utf-8 -*-

from django.views import generic

from .models import Picture

class ImageView(generic.ListView):
    """
        This view is the gallery of the website with all the pictures taken.
    """
    model = Picture
    template_name = 'article/gallery.html'
    context_object_name = 'images'

cvpvcBlog/apps/viewer/views.py
from django.shortcuts import render

# Create your views here.

cvpvcBlog/templates/mini_url/index.html
{% extends 'website.html' %}
{% load static %}

{% block style %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/style_miniurl.css' %}">
{% endblock %}

{% block title %}
Little URL Shortener
{% endblock %}

{% block nav %}
<div class="container-full">
    <nav class='navbar navbar-inverse container'>
        <div class="navbar-header">
            <a href="{% url 'miniurl:index' %}" class="navbar-brand">Homemade URL shortener</a>
        </div>
        <ul class='nav navbar-nav navbar-right'>
            <li><a href="{% url 'miniurl:full_list' %}">Full list of shortened URLs</a></li>
            <li><a href="{% url 'miniurl:new_url' %}">Shorten a URL</a></li>
            <li><a href="/">Back to the Blog</a></li>
        </ul>
    </nav>
</div>
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}

cvpvcBlog/templates/mini_url/miniurl_form.html
{% extends 'mini_url/index.html' %}

{% block content %}
<div class="container text-center">
    <p class="row">
        {% if status %}
            {{ status }}
            {% ifequal status 'URL saved' %}
                <br>
                <a href="{% url 'miniurl:short' miniurl.code %}">{{ request.get_host }}{% url 'miniurl:short' mini_url.code %}</a>
            {% endifequal %}
        {% endif %}
    </p>
</div>

<div class="container text-center">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <form action="{% url 'miniurl:new_url' %}" method="post">
            {% csrf_token %}    
            {% comment %}
            {% for fields in form %}
                {{ fields }}
            {% endfor %}  
            <br><br><br>  
            {% endcomment %}
            {{ form.as_p }}
            <div style="margin-top:30px">
                <a href="{% url 'miniurl:index' %}" class="btn btn-info">Retour</a>
                <input type="submit" value="Submit" class="btn btn-info">
            </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

cvpvcBlog/templates/mini_url/miniurl_list.html
{% extends 'mini_url/index.html' %}

{% block content %}
<div class="container">
    <p class="row">
        <h4 class="text-center">Back to the main page ?</h4>
        <div class="text-center"><a href="{% url 'miniurl:index' %}" class="btn btn-info">Here !</a></div>
    </p>

    <h3 class="text-center">5 previous URL shortened</h3>
    {% for mini_url in full_mini_url_list %}
        <dl class="text-center">
            <dt>
                {% if mini_url.title == 'Page Not Found' %}
                    Page Not Found, url = {{ mini_url.long_url }}
                {% else %}
                    {{ mini_url.title }}
                {% endif %}
                - <a href="{% url 'miniurl:short' mini_url.code %}">{{ request.get_host }}{% url 'miniurl:short' mini_url.code %}</a>
            </dt>
            <dd>
                créé le {{ mini_url.date_creation }} 
                {% if mini_url.pseudo %}
                    par <strong>{{ mini_url.pseudo }}</strong>
                {% endif %}
                et accédé {{ mini_url.nb_of_access }} fois
            </dd>
        </dl>
    {% empty %}
        <div>No URL to show</div>
    {% endfor %}
    </ul>
</div>
{% endblock %}

cvpvcBlog/templates/mini_url/welcome_page.html
{% extends 'mini_url/index.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <h3 class="text-center">5 previous URL shortened</h3>
        {% for mini_url in latest_mini_url_list %}
        <dl class="text-center">
            <dt>
                {% if mini_url.title == 'Page Not Found' %}
                Page Not Found, url = {{ mini_url.long_url }}
                {% else %}
                {{ mini_url.title }}
                {% endif %}
                - <a href="{% url 'miniurl:short' mini_url.code %}">{{ mini_url.code }}</a>
            </dt>
            <dd>
                créé le {{ mini_url.date_creation|date:"d M Y à G:i" }} 
                {% if mini_url.pseudo %}
                par <strong>{{ mini_url.pseudo }}</strong>
                {% endif %}
                et accédé {{ mini_url.nb_of_access }} fois
            </dd>
        </dl>
        {% empty %}
        <div class="text-center">No URL to show</div>
        {% endfor %}
        <div class="row">
            {% if latest_mini_url_list %}
            <div class="col-md-offset-2 col-md-4">
                <h4 class="text-center">Want to see the full list ?</h4>
                <div class="text-center"><a href="{% url 'miniurl:full_list' %}" class="btn btn-info">Here !</a></div>
            </div>
            <div class="col-md-4">
                {% else %}
                <div>
                    {% endif %}
                    <h4 class="text-center">Want to shorten a URL ?</h3>
                    <div class="text-center"><a href="{% url 'miniurl:new_url' %}" class='btn btn-info' role="button">Here !</a></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}